# coding=utf-8
__author__ = 'pawel'

powiaty = [{"provinceName": "Dolnośląskie",
            "counties": [( "Bolesławiecki", ["Legnicki", "Lubański", "Lwówecki", "Polkowicki", "Zgorzelecki", "Złotoryjski", "Żagański"] ),
                         ( "Dzierżoniowski", ["Kłodzki", "Strzeliński", "Świdnicki", "Wadowicki", "Wrocławski", "Ząbkowicki"] ),
                         ( "Głogowski", ["Górowski", "Lubiński", "Nowosolski", "Polkowicki", "Wschowski"] ),
                         ( "Górowski", ["Głogowski", "Leszczyński", "Lubiński", "Rawicki", "Trzebnicki", "Wołowski", "Wschowski"] ),
                         ( "Jaworski", ["Jeleniogórski", "Kamiennogórski", "Legnicki", "Średzki", "Świdnicki", "Wałbrzyski", "Złotoryjski"] ),
                         ( "Jeleniogórski", ["Jaworski", "m. Jelenia Góra", "Kamiennogórski", "Lwówecki", "Złotoryjski"] ),
                         ( "Kamiennogórski", ["Jaworski", "Jeleniogórski", "Wałbrzyski"] ),
                         ( "Kłodzki", ["Dzierżoniowski", "Wałbrzyski", "Ząbkowicki"] ),
                         ( "Legnicki", ["Bolesławiecki", "Jaworski", "m. Legnica", "Lubiński", "Polkowicki", "Średzki", "Wołowski", "Złotoryjski"] ),
                         ( "Lubański", ["Bolesławiecki", "Lwówecki", "Zgorzelecki"] ),
                         ( "Lubiński", ["Głogowski", "Górowski", "Legnicki", "Polkowicki", "Wołowski"] ),
                         ( "Lwówecki", ["Bolesławiecki", "Jeleniogórski", "Lubański", "Złotoryjski"] ),
                         ( "Milicki", ["Krotoszyński", "Oleśnicki", "Ostrowski", "Rawicki", "Trzebnicki"] ),
                         ( "Oławski", ["Brzeski", "Namysłowski", "Oleśnicki", "Strzeliński", "Wrocławski"] ),
                         ( "Oleśnicki", ["Kępiński", "Milicki", "Namysłowski", "Oławski", "Ostrowski", "Ostrzeszowski", "Trzebnicki", "Wrocławski"] ),
                         ( "Polkowicki", ["Bolesławiecki", "Głogowski", "Legnicki", "Lubiński", "Żagański"] ),
                         ( "Strzeliński", ["Brzeski", "Dzierżoniowski", "Nyski", "Oławski", "Wrocławski", "Ząbkowicki"] ),
                         ( "Średzki", ["Jaworski", "Legnicki", "Świdnicki", "Trzebnicki", "Wołowski", "Wrocławski", "m. Wrocław"] ),
                         ( "Świdnicki", ["Dzierżoniowski", "Jaworski", "Średzki", "Wałbrzyski", "Wrocławski"] ),
                         ( "Trzebnicki", ["Górowski", "Milicki", "Oleśnicki", "Rawicki", "Średzki", "Wołowski", "Wrocławski", "m. Wrocław"] ),
                         ( "Wałbrzyski", ["Dzierżoniowski", "Jaworski", "Kamiennogórski", "Kłodzki", "Świdnicki"] ),
                         ( "Wołowski", ["Górowski", "Legnicki", "Lubiński", "Średzki", "Trzebnicki"] ),
                         ( "Wrocławski", ["Dzierżoniowski", "Oleśnicki", "Oławski", "Strzeliński", "Średzki", "Świdnicki", "Trzebnicki", "m. Wrocław"] ),
                         ( "Ząbkowicki", ["Dzierżoniowski", "Kłodzki", "Nyski", "Strzeliński"] ),
                         ( "Zgorzelecki", ["Bolesławiecki", "Lubański", "Żagański", "Żarski"] ),
                         ( "Złotoryjski", ["Bolesławiecki", "Jaworski", "Jeleniogórski", "Legnicki", "Lwówecki"] )]},
           {"provinceName": "Kujawsko-Pomorskie",
            "counties": [( "Aleksandrowski", ["Inowrocławski", "Lipnowski", "Radziejowski", "Toruński", "Włocławski"] ),
                         ( "Brodnicki", ["Działdowski", "Golubsko-Dobrzyński", "Grudziądzki", "Nowomiejski", "Rypiński", "Wąbrzeski", "Żuromiński"] ),
                         ( "Bydgoski", ["m. Bydgoszcz", "Chełmiński", "Inowrocławski", "Nakielski", "Sępoleński", "Świecki", "Toruński", "Tucholski", "Żniński"] ),
                         ( "Chełmiński", ["Bydgoski", "Grudziądzki", "Świecki", "Toruński", "Wąbrzeski"] ),
                         ( "Golubsko-Dobrzyński", ["Brodnicki", "Lipnowski", "Rypiński", "Toruński", "Wąbrzeski"] ),
                         ( "Grudziądzki", ["Brodnicki", "Chełmiński", "m. Grudziądz", "Iławski", "Kwidzyński", "Nowomiejski", "Świecki", "Wąbrzeski"] ),
                         ( "Inowrocławski", ["Aleksandrowski", "Bydgoski", "Mogileński", "Radziejowski", "Toruński", "Żniński"] ),
                         ( "Lipnowski", ["Aleksandrowski", "Golubsko-Dobrzyński", "Płocki", "Rypiński", "Sierpecki", "Toruński", "Włocławski", "m. Włocławek"] ),
                         ( "Mogileński", ["Gnieźnieński", "Inowrocławski", "Koniński", "Słupecki", "Żniński"] ),
                         ( "Nakielski", ["Bydgoski", "Chodzieski", "Sępoleński", "Wągrowiecki", "Żniński"] ),
                         ( "Radziejowski", ["Aleksandrowski", "Inowrocławski", "Kolski", "Koniński", "Włocławski"] ),
                         ( "Rypiński", ["Brodnicki", "Golubsko-Dobrzyński", "Lipnowski", "Sierpecki", "Żuromiński"] ),
                         ( "Sępoleński", ["Bydgoski", "Chojnicki", "Człuchowski", "Nakielski", "Pilski", "Tucholski", "Złotowski"] ),
                         ( "Świecki", ["Bydgoski", "Chełmiński", "Grudziądzki", "m. Grudziądz", "Kwidzyński", "Starogardzki", "Tucholski"] ),
                         ( "Toruński", ["Aleksandrowski", "Bydgoski", "m. Bydgoszcz", "Chełmiński", "Golubsko-Dobrzyński", "Inowrocławski", "Lipnowski", "m. Toruń", "Wąbrzeski"] ),
                         ( "Tucholski", ["Bydgoski", "Chojnicki", "Sępoleński", "Starogardzki", "Świecki"] ),
                         ( "Wąbrzeski", ["Brodnicki", "Chełmiński", "Golubsko-Dobrzyński", "Grudziądzki", "Toruński"] ),
                         ( "Włocławski", ["Aleksandrowski", "Gostyniński", "Kolski", "Kutnowski", "Lipnowski", "Płocki", "Radziejowski", "m. Włocławek"] ),
                         ( "Żniński", ["Bydgoski", "Gnieźnieński", "Inowrocławski", "Mogileński", "Nakielski", "Wągrowiecki"] )]},
           {"provinceName": "Lubelskie",
            "counties": [( "Bialski", ["m. Biała Podlaska", "Łosicki", "Łukowski", "Parczewski", "Radzyński", "Siedlecki", "Siemiatycki", "Włodawski"] ),
                         ( "Biłgorajski", ["Janowski", "Krasnostawski", "Leżajski", "Lubaczowski", "Lubelski", "Niżański", "Przeworski", "Tomaszowski", "Zamojski"] ),
                         ( "Chełmski", ["m. Chełm", "Hrubieszowski", "Krasnostawski", "Łęczyński", "Świdnicki", "Włodawski", "Zamojski"] ),
                         ( "Hrubieszowski", ["Chełmski", "Tomaszowski", "Zamojski"] ),
                         ( "Janowski", ["Biłgorajski", "Kraśnicki", "Lubelski", "Niżański", "Stalowowolski"] ),
                         ( "Krasnostawski", ["Biłgorajski", "Chełmski", "Lubelski", "Świdnicki", "Zamojski"] ),
                         ( "Kraśnicki", ["Janowski", "Lubelski", "Opatowski", "Opolski", "Sandomierski", "Stalowowolski"] ),
                         ( "Łęczyński", ["Chełmski", "Lubartowski", "Lubelski", "Parczewski", "Świdnicki", "Włodawski"] ),
                         ( "Lubartowski", ["Lubelski", "Łęczyński", "Łukowski", "Parczewski", "Puławski", "Radzyński", "Rycki"] ),
                         ( "Lubelski", ["Biłgorajski", "Janowski", "Krasnostawski", "Kraśnicki", "Lubartowski", "m. Lublin", "Łęczyński", "Opolski", "Puławski", "Świdnicki"] ),
                         ( "Łukowski", ["Bialski", "Garwoliński", "Lubartowski", "Radzyński", "Rycki", "Siedlecki"] ),
                         ( "Opolski", ["Kraśnicki", "Lipski", "Lubelski", "Opatowski", "Puławski"] ),
                         ( "Parczewski", ["Bialski", "Lubartowski", "Łęczyński", "Radzyński", "Włodawski"] ),
                         ( "Puławski", ["Kozienicki", "Lubartowski", "Lubelski", "Opolski", "Rycki", "Zwoleński"] ),
                         ( "Radzyński", ["Bialski", "Lubartowski", "Łukowski", "Parczewski"] ),
                         ( "Rycki", ["Garwoliński", "Kozienicki", "Lubartowski", "Łukowski", "Puławski"] ),
                         ( "Świdnicki", ["Chełmski", "Krasnostawski", "Lubelski", "m. Lublin", "Łęczyński"] ),
                         ( "Tomaszowski", ["Biłgorajski", "Hrubieszowski", "Lubaczowski", "Zamojski"] ),
                         ( "Włodawski", ["Bialski", "Chełmski", "Łęczyński", "Parczewski"] ),
                         ( "Zamojski", ["Biłgorajski", "Chełmski", "Hrubieszowski", "Krasnostawski", "Tomaszowski", "m. Zamość"] )]},
           {"provinceName": "Lubuskie",
            "counties": [( "Gorzowski", ["m. Gorzów Wielkopolski", "Międzyrzecki", "Myśliborski", "Strzelecko-Drezdenecki", "Sulęciński"] ),
                         ( "Krośnieński", ["Słubicki", "Sulęciński", "Świebodziński", "Zielonogórski", "Żarski"] ),
                         ( "Międzyrzecki", ["Gorzowski", "Międzychodzki", "Nowotomyski", "Strzelecko-Drezdenecki", "Sulęciński", "Świebodziński"] ),
                         ( "Nowosolski", ["Głogowski", "Wolsztyński", "Wschowski", "Zielonogórski", "Żagański"] ),
                         ( "Słubicki", ["Krośnieński", "Sulęciński"] ),
                         ( "Strzelecko-Drezdenecki", ["Choszczeński", "Czarnkowsko-Trzcianecki", "Gorzowski", "Międzychodzki", "Międzyrzecki", "Myśliborski", "Wałecki"] ),
                         ( "Sulęciński", ["Gorzowski", "Krośnieński", "Międzyrzecki", "Słubicki", "Świebodziński"] ),
                         ( "Świebodziński", ["Krośnieński", "Międzyrzecki", "Nowotomyski", "Sulęciński", "Zielonogórski"] ),
                         ( "Wschowski", ["Głogowski", "Górowski", "Leszczyński", "Nowosolski", "Wolsztyński"] ),
                         ( "Zielonogórski", ["Krośnieński", "Nowosolski", "Nowotomyski", "Świebodziński", "Wolsztyński", "m. Zielona Góra", "Żagański", "Żarski"] ),
                         ( "Żagański", ["Bolesławiecki", "Nowosolski", "Polkowicki", "Zgorzelecki", "Zielonogórski", "Żarski"] ),
                         ( "Żarski", ["Krośnieński", "Zgorzelecki", "Zielonogórski", "Żagański"] )]},
           {"provinceName": "Łódzkie",
            "counties": [( "Bełchatowski", ["Łaski", "Pabianicki", "Pajęczański", "Piotrkowski", "Radomszczański", "Wieluński"] ),
                         ( "Brzeziński", ["Łowicki", "Łódzki Wschodni", "Skierniewicki", "Tomaszowski", "Zgierski"] ),
                         ( "Kutnowski", ["Gostyniński", "Kolski", "Łęczycki", "Łowicki", "Włocławski"] ),
                         ( "Łaski", ["Bełchatowski", "Pabianicki", "Sieradzki", "Wieluński", "Zduńskowolski"] ),
                         ( "Łęczycki", ["Kolski", "Kutnowski", "Łowicki", "Poddębicki", "Zgierski"] ),
                         ( "Łódzki Wschodni", ["Brzeziński", "m. Łódź", "Pabianicki", "Piotrkowski", "Tomaszowski", "Zgierski"] ),
                         ( "Łowicki", ["Brzeziński", "Gostyniński", "Kutnowski", "Łęczycki", "Skierniewicki", "Sochaczewski", "Zgierski"] ),
                         ( "Opoczyński", ["Konecki", "Piotrkowski", "Przysuski", "Tomaszowski"] ),
                         ( "Pabianicki", ["Bełchatowski", "Łaski", "m. Łódź", "Łódzki Wschodni", "Piotrkowski", "Poddębicki", "Zgierski"] ),
                         ( "Pajęczański", ["Bełchatowski", "Częstochowski", "Kłobucki", "Radomszczański", "Wieluński"] ),
                         ( "Piotrkowski", ["Bełchatowski", "Łódzki Wschodni", "Opoczyński", "Pabianicki", "m. Piotrków Trybunalski", "Radomszczański", "Tomaszowski"] ),
                         ( "Poddębicki", ["Kolski", "Łaski", "Łęczycki", "Pabianicki", "Sieradzki", "Turecki", "Zduńskowolski", "Zgierski"] ),
                         ( "Radomszczański", ["Bełchatowski", "Częstochowski", "Konecki", "Pajęczański", "Piotrkowski", "Włoszczowski"] ),
                         ( "Rawski", ["Grójecki", "Skierniewicki", "Tomaszowski", "Żyrardowski"] ),
                         ( "Sieradzki", ["Kaliski", "Łaski", "Ostrzeszowski", "Poddębicki", "Turecki", "Wieluński", "Wieruszowski", "Zduńskowolski"] ),
                         ( "Skierniewicki", ["Brzeziński", "Łowicki", "Rawski", "m. Skierniewice", "Sochaczewski", "Tomaszowski", "Żyrardowski"] ),
                         ( "Tomaszowski", ["Brzeziński", "Grójecki", "Łódzki Wschodni", "Opoczyński", "Piotrkowski", "Rawski", "Skierniewicki"] ),
                         ( "Wieluński", ["Bełchatowski", "Kłobucki", "Łaski", "Oleski", "Pajęczański", "Sieradzki", "Wieruszowski"] ),
                         ( "Wieruszowski", ["Kępiński", "Kluczborski", "Oleski", "Ostrzeszowski", "Sieradzki", "Wieluński"] ),
                         ( "Zduńskowolski", ["Łaski", "Poddębicki", "Sieradzki"] ),
                         ( "Zgierski", ["Brzeziński", "Łęczycki", "Łowicki", "m. Łódź", "Łódzki Wschodni", "Pabianicki", "Poddębicki"] )]},
           {"provinceName": "Małopolskie",
            "counties": [( "Bocheński", ["Brzeski", "Krakowski", "Limanowski", "Myślenicki", "Proszowicki", "Wielicki"] ),
                         ( "Brzeski", ["Bocheński", "Limanowski", "Nowosądecki", "Proszowicki", "Tarnowski"] ),
                         ( "Chrzanowski", ["m. Jaworzno", "Krakowski", "Olkuski", "Oświęcimski", "Wadowicki"] ),
                         ( "Dąbrowski", ["Buski", "Kazimierski", "Mielecki", "Staszowski", "Tarnowski"] ),
                         ( "Gorlicki", ["Jasielski", "Nowosądecki", "Tarnowski"] ),
                         ( "Krakowski", ["Bocheński", "Chrzanowski", "m. Kraków", "Miechowski", "Myślenicki", "Olkuski", "Proszowicki", "Wadowicki", "Wielicki"] ),
                         ( "Limanowski", ["Bocheński", "Brzeski", "Myślenicki", "Nowosądecki", "Nowotarski"] ),
                         ( "Miechowski", ["Krakowski", "Jędrzejowski", "Kazimierski", "Olkuski", "Pińczowski", "Proszowicki", "Zawierciański"] ),
                         ( "Myślenicki", ["Bocheński", "Krakowski", "Limanowski", "Nowotarski", "Suski", "Wadowicki", "Wielicki"] ),
                         ( "Nowosądecki", ["Bocheński", "Brzeski", "Gorlicki", "Myślenicki", "m. Nowy Sącz", "Nowotarski", "Tarnowski"] ),
                         ( "Nowotarski", ["Limanowski", "Myślenicki", "Nowosądecki", "Suski", "Tatrzański"] ),
                         ( "Olkuski", ["Będziński", "Chrzanowski", "m. Dąbrowa Górnicza", "m. Jaworzno", "Krakowski", "Miechowski", "Zawierciański"] ),
                         ( "Oświęcimski", ["Bielski", "Chrzanowski", "m. Jaworzno", "Pszczyński", "Bieruńsko-Lędziński", "Wadowicki"] ),
                         ( "Proszowicki", ["Bocheński", "Brzeski", "Kazimierski", "Krakowski", "Miechowski", "Tarnowski"] ),
                         ( "Suski", ["Myślenicki", "Nowotarski", "Wadowicki", "Żywiecki"] ),
                         ( "Tarnowski", ["Brzeski", "Dąbrowski", "Dębicki", "Gorlicki", "Jasielski", "Kazimierski", "Nowosądecki", "m. Tarnów"] ),
                         ( "Tatrzański", ["Nowotarski"] ),
                         ( "Wadowicki", ["Bielski", "Chrzanowski", "Krakowski", "Myślenicki", "Oświęcimski", "Suski", "Żywiecki"] ),
                         ( "Wielicki", ["Bocheński", "Krakowski", "m. Kraków", "Myślenicki"] )]},
           {"provinceName": "Mazowieckie",
            "counties": [( "Białobrzeski", ["Grójecki", "Kozienicki", "Przysuski", "Radomski"] ),
                         ( "Ciechanowski", ["Makowski", "Mławski", "Płoński", "Przasnyski", "Pułtuski"] ),
                         ( "Garwoliński", ["Kozienicki", "Łukowski", "Miński", "Otwocki", "Rycki"] ),
                         ( "Gostyniński", ["Kutnowski", "Łowicki", "Płocki", "Sochaczewski", "Włocławski"] ),
                         ( "Grodziski", ["Grójecki", "Pruszkowski", "Sochaczewski", "Warszawski Zachodni", "Żyrardowski"] ),
                         ( "Grójecki", ["Białobrzeski", "Grodziski", "Kozienicki", "Otwocki", "Piaseczyński", "Pruszkowski", "Przysuski", "Rawski", "Tomaszowski", "Żyrardowski"] ),
                         ( "Kozienicki", ["Białobrzeski", "Garwoliński", "Grójecki", "Puławski", "Radomski", "Rycki", "Zwoleński"] ),
                         ( "Legionowski", ["Nowodworski", "Pułtuski", "m.st. Warszawa", "Warszawski Zachodni", "Wołomiński", "Wyszkowski"] ),
                         ( "Lipski", ["Opatowski", "Opolski", "Ostrowiecki", "Radomski", "Starachowicki", "Zwoleński"] ),
                         ( "Łosicki", ["Bielski", "Siedlecki", "Siemiatycki"] ),
                         ( "Makowski", ["Ciechanowski", "Ostrołęcki", "Przasnyski", "Pułtuski", "Wyszkowski"] ),
                         ( "Miński", ["Garwoliński", "Otwocki", "Siedlecki", "m.st. Warszawa", "Węgrowski", "Wołomiński"] ),
                         ( "Mławski", ["Ciechanowski", "Działdowski", "Nidzicki", "Płoński", "Przasnyski", "Żuromiński"] ),
                         ( "Nowodworski", ["Legionowski", "Płoński", "Pułtuski", "Sochaczewski", "Warszawski Zachodni"] ),
                         ( "Ostrołęcki", ["Kolneński", "Łomżyński", "Makowski", "m. Ostrołęka", "Ostrowski", "Przasnyski", "Szczycieński", "Wyszkowski"] ),
                         ( "Ostrowski", ["Ostrołęcki", "Sokołowski", "Węgrowski", "Wysokomazowiecki", "Wyszkowski", "Zambrowski"] ),
                         ( "Otwocki", ["Garwoliński", "Grójecki", "Miński", "Piaseczyński", "m.st. Warszawa"] ),
                         ( "Piaseczyński", ["Grójecki", "Otwocki", "Pruszkowski", "m.st. Warszawa"] ),
                         ( "Płocki", ["Gostyniński", "Lipnowski", "m. Płock", "Płoński", "Sierpecki", "Sochaczewski", "Włocławski"] ),
                         ( "Płoński", ["Ciechanowski", "Mławski", "Nowodworski", "Płocki", "Pułtuski", "Sierpecki", "Sochaczewski", "Żuromiński"] ),
                         ( "Pruszkowski", ["Grodziski", "Grójecki", "Piaseczyński", "m.st. Warszawa", "Warszawski Zachodni"] ),
                         ( "Przasnyski", ["Ciechanowski", "Makowski", "Mławski", "Nidzicki", "Ostrołęcki", "Szczycieński"] ),
                         ( "Przysuski", ["Białobrzeski", "Grójecki", "Konecki", "Opoczyński", "Radomski", "Szydłowiecki"] ),
                         ( "Pułtuski", ["Ciechanowski", "Legionowski", "Makowski", "Nowodworski", "Płoński", "Wyszkowski"] ),
                         ( "Radomski", ["Białobrzeski", "Kozienicki", "Lipski", "Przysuski", "m. Radom", "Starachowicki", "Szydłowiecki", "Zwoleński"] ),
                         ( "Siedlecki", ["Bialski", "Łosicki", "Łukowski", "Miński", "m. Siedlce", "Siemiatycki", "Sokołowski", "Węgrowski"] ),
                         ( "Sierpecki", ["Lipnowski", "Płocki", "Płoński", "Rypiński", "Żuromiński"] ),
                         ( "Sochaczewski", ["Gostyniński", "Grodziski", "Łowicki", "Nowodworski", "Płocki", "Płoński", "Skierniewicki", "Warszawski Zachodni", "Żyrardowski"] ),
                         ( "Sokołowski", ["Ostrowski", "Siedlecki", "Siemiatycki", "Węgrowski", "Wysokomazowiecki"] ),
                         ( "Szydłowiecki", ["Konecki", "Przysuski", "Radomski", "Skarżyski", "Starachowicki"] ),
                         ( "Warszawski Zachodni", ["Grodziski", "Legionowski", "Nowodworski", "Pruszkowski", "Sochaczewski", "m.st. Warszawa"] ),
                         ( "Węgrowski", ["Miński", "Ostrowski", "Siedlecki", "Sokołowski", "Wołomiński", "Wyszkowski"] ),
                         ( "Wołomiński", ["Legionowski", "Miński", "m.st. Warszawa", "Węgrowski", "Wyszkowski"] ),
                         ( "Wyszkowski", ["Legionowski", "Makowski", "Ostrołęcki", "Ostrowski", "Pułtuski", "Węgrowski", "Wołomiński"] ),
                         ( "Zwoleński", ["Kozienicki", "Lipski", "Puławski", "Radomski"] ),
                         ( "Żuromiński", ["Brodnicki", "Działdowski", "Mławski", "Płoński", "Rypiński", "Sierpecki"] ),
                         ( "Żyrardowski", ["Grodziski", "Grójecki", "Rawski", "Skierniewicki", "Sochaczewski"] )]},
           {"provinceName": "Opolskie",
            "counties": [( "Brzeski", ["Namysłowski", "Nyski", "Oławski", "Opolski", "Strzeliński"] ),
                         ( "Głubczycki", ["Kędzierzyńsko-Kozielski", "Prudnicki", "Raciborski"] ),
                         ( "Kędzierzyńsko-Kozielski", ["Gliwicki", "Głubczycki", "Krapkowicki", "Prudnicki", "Raciborski", "Strzelecki"] ),
                         ( "Kluczborski", ["Kępiński", "Namysłowski", "Oleski", "Opolski", "Wieruszowski"] ),
                         ( "Krapkowicki", ["Kędzierzyńsko-Kozielski", "Opolski", "Prudnicki", "Strzelecki"] ),
                         ( "Namysłowski", ["Brzeski", "Kępiński", "Kluczborski", "Oleśnicki", "Oławski", "Opolski"] ),
                         ( "Nyski", ["Brzeski", "Opolski", "Prudnicki", "Strzeliński", "Ząbkowicki"] ),
                         ( "Oleski", ["Kluczborski", "Kłobucki", "Lubliniecki", "Opolski", "Strzelecki", "Wieluński", "Wieruszowski"] ),
                         ( "Opolski", ["Brzeski", "Kluczborski", "Krapkowicki", "Namysłowski", "Nyski", "Oleski", "m. Opole", "Prudnicki", "Strzelecki"] ),
                         ( "Prudnicki", ["Głubczycki", "Kędzierzyńsko-Kozielski", "Krapkowicki", "Nyski", "Opolski"] ),
                         ( "Strzelecki", ["Gliwicki", "Kędzierzyńsko-Kozielski", "Krapkowicki", "Lubliniecki", "Oleski", "Opolski", "Tarnogórski"] )]},
           {"provinceName": "Podkarpackie",
            "counties": [( "Bieszczadzki", ["Leski", "Przemyski"] ),
                         ( "Brzozowski", ["Krośnieński", "Przemyski", "Rzeszowski", "Sanocki", "Strzyżowski"] ),
                         ( "Dębicki", ["Jasielski", "Mielecki", "Ropczycko-Sędziszowski", "Strzyżowski", "Tarnowski"] ),
                         ( "Jarosławski", ["Lubaczowski", "Przemyski", "Przeworski"] ),
                         ( "Jasielski", ["Dębicki", "Gorlicki", "Krośnieński", "Strzyżowski", "Tarnowski"] ),
                         ( "Kolbuszowski", ["Mielecki", "Niżański", "Ropczycko-Sędziszowski", "Rzeszowski", "Stalowowolski", "Tarnobrzeski"] ),
                         ( "Krośnieński", ["Brzozowski", "Jasielski", "m. Krosno", "Sanocki", "Strzyżowski"] ),
                         ( "Łańcucki", ["Leżajski", "Przeworski", "Rzeszowski"] ),
                         ( "Leski", ["Bieszczadzki", "Przemyski", "Sanocki"] ),
                         ( "Leżajski", ["Biłgorajski", "Łańcucki", "Niżański", "Przeworski", "Rzeszowski"] ),
                         ( "Lubaczowski", ["Biłgorajski", "Jarosławski", "Przeworski", "Tomaszowski"] ),
                         ( "Mielecki", ["Dąbrowski", "Dębicki", "Kolbuszowski", "Ropczycko-Sędziszowski", "Staszowski", "Tarnobrzeski"] ),
                         ( "Niżański", ["Biłgorajski", "Janowski", "Kolbuszowski", "Leżajski", "Rzeszowski", "Stalowowolski"] ),
                         ( "Przemyski", ["Bieszczadzki", "Brzozowski", "Jarosławski", "Leski", "m. Przemyśl", "Przeworski", "Rzeszowski", "Sanocki"] ),
                         ( "Przeworski", ["Biłgorajski", "Jarosławski", "Leżajski", "Lubaczowski", "Łańcucki", "Przemyski", "Rzeszowski"] ),
                         ( "Ropczycko-Sędziszowski", ["Dębicki", "Kolbuszowski", "Mielecki", "Rzeszowski", "Strzyżowski"] ),
                         ( "Rzeszowski", ["Brzozowski", "Kolbuszowski", "Leżajski", "Łańcucki", "Niżański", "Przemyski", "Przeworski", "Ropczycko-Sędziszowski", "m. Rzeszów", "Strzyżowski"] ),
                         ( "Sanocki", ["Brzozowski", "Krośnieński", "Leski", "Przemyski"] ),
                         ( "Stalowowolski", ["Janowski", "Kolbuszowski", "Kraśnicki", "Niżański", "Sandomierski", "Tarnobrzeski"] ),
                         ( "Strzyżowski", ["Brzozowski", "Dębicki", "Jasielski", "Krośnieński", "Ropczycko-Sędziszowski", "Rzeszowski"] ),
                         ( "Tarnobrzeski", ["Kolbuszowski", "Mielecki", "Sandomierski", "Stalowowolski", "m. Tarnobrzeg"] )]},
           {"provinceName": "Podlaskie",
            "counties": [( "Augustowski", ["Ełcki", "Grajewski", "Moniecki", "Olecki", "Sejneński", "Sokólski", "Suwalski"] ),
                         ( "Białostocki", ["m. Białystok", "Bielski", "Hajnowski", "Moniecki", "Sokólski", "Wysokomazowiecki", "Zambrowski"] ),
                         ( "Bielski", ["Białostocki", "Hajnowski", "Siemiatycki", "Wysokomazowiecki"] ),
                         ( "Grajewski", ["Augustowski", "Ełcki", "Kolneński", "Łomżyński", "Moniecki", "Piski"] ),
                         ( "Hajnowski", ["Białostocki", "Bielski", "Siemiatycki"] ),
                         ( "Kolneński", ["Grajewski", "Łomżyński", "Ostrołęcki", "Piski"] ),
                         ( "Łomżyński", ["Grajewski", "Kolneński", "m. Łomża", "Moniecki", "Ostrołęcki", "Zambrowski"] ),
                         ( "Moniecki", ["Augustowski", "Białostocki", "Grajewski", "Łomżyński", "Sokólski"] ),
                         ( "Sejneński", ["Augustowski", "Suwalski"] ),
                         ( "Siemiatycki", ["Bielski", "Hajnowski", "Łosicki", "Siedlecki", "Sokołowski", "Wysokomazowiecki"] ),
                         ( "Sokólski", ["Augustowski", "Białostocki", "Moniecki"] ),
                         ( "Suwalski", ["Augustowski", "Ełcki", "Gołdapski", "Olecki", "Sejneński", "m. Suwałki"] ),
                         ( "Wysokomazowiecki", ["Białostocki", "Bielski", "Ostrowski", "Siemiatycki", "Zambrowski"] ),
                         ( "Zambrowski", ["Białostocki", "Łomżyński", "Ostrowski"] )]},
           {"provinceName": "Pomorskie",
            "counties": [( "Bytowski", ["Chojnicki", "Człuchowski", "Kartuski", "Koszaliński", "Kościerski", "Lęborski", "Słupski", "Szczecinecki"] ),
                         ( "Chojnicki", ["Bytowski", "Człuchowski", "Kościerski", "Sępoleński", "Starogardzki", "Tucholski"] ),
                         ( "Człuchowski", ["Bytowski", "Chojnicki", "Sępoleński", "Szczecinecki", "Złotowski"] ),
                         ( "Gdański", ["m. Gdańsk", "Kartuski", "Kościerski", "Nowodworski", "Starogardzki", "Tczewski"] ),
                         ( "Kartuski", ["Bytowski", "Gdański", "m. Gdańsk", "m. Gdynia", "Kościerski", "Lęborski", "Wejherowski"] ),
                         ( "Kościerski", ["Bytowski", "Chojnicki", "Gdański", "Kartuski", "Starogardzki"] ),
                         ( "Kwidzyński", ["Grudziądzki", "Iławski", "Sztumski", "Świecki", "Tczewski"] ),
                         ( "Lęborski", ["Bytowski", "Kartuski", "Słupski", "Wejherowski"] ),
                         ( "Malborski", ["Elbląski", "Gdański", "Nowodworski", "Sztumski", "Tczewski"] ),
                         ( "Nowodworski", ["Elbląski", "Gdański", "m. Gdańsk", "Malborski"] ),
                         ( "Pucki", ["m. Gdynia", "Wejherowski"] ),
                         ( "Słupski", ["Bytowski", "Koszaliński", "Lęborski", "Sławieński", "m. Słupsk"] ),
                         ( "Starogardzki", ["Chojnicki", "Gdański", "Kościerski", "Świecki", "Tczewski", "Tucholski"] ),
                         ( "Sztumski", ["Elbląski", "Iławski", "Kwidzyński", "Malborski", "Ostródzki", "Tczewski"] ),
                         ( "Tczewski", ["Gdański", "Kwidzyński", "Malborski", "Starogardzki", "Sztumski", "Świecki"] ),
                         ( "Wejherowski", ["m. Gdynia", "Kartuski", "Lęborski", "Pucki"] )]},
           {"provinceName": "Śląskie",
            "counties": [( "Będziński", ["m. Dąbrowa Górnicza", "m. Katowice", "Myszkowski", "Olkuski", "m. Piekary Śląskie", "m. Siemianowice Śląskie", "Tarnogórski", "Zawierciański"] ),
                         ( "Bielski", ["m. Bielsko-Biała", "Cieszyński", "Oświęcimski", "Pszczyński", "Wadowicki", "Żywiecki"] ),
                         ( "Bieruńsko-Lędziński", ["m. Jaworzno", "m. Katowice", "Mikołowski", "m. Mysłowice", "Oświęcimski", "Pszczyński", "m. Tychy"] ),
                         ( "Cieszyński", ["Bielski", "m. Bielsko-Biała", "m. Jastrzębie-Zdrój", "Pszczyński", "Żywiecki"] ),
                         ( "Częstochowski", ["m. Częstochowa", "Kłobucki", "Lubliniecki", "Myszkowski", "Pajęczański", "Radomszczański", "Włoszczowski", "Zawierciański"] ),
                         ( "Gliwicki", ["m. Gliwice", "Kędzierzyńsko-Kozielski", "Mikołowski", "Raciborski", "Rybnicki", "m. Rybnik", "Strzelecki", "Tarnogórski", "m. Zabrze"] ),
                         ( "Kłobucki", ["Częstochowski", "m. Częstochowa", "Lubliniecki", "Oleski", "Pajęczański", "Wieluński"] ),
                         ( "Lubliniecki", ["Częstochowski", "Kłobucki", "Myszkowski", "Oleski", "Strzelecki", "Tarnogórski"] ),
                         ( "Mikołowski", ["Gliwicki", "m. Katowice", "Pszczyński", "m. Ruda Śląska", "Rybnicki", "m. Tychy", "m. Żory"] ),
                         ( "Myszkowski", ["Będziński", "Częstochowski", "Lubliniecki", "Tarnogórski", "Zawierciański"] ),
                         ( "Pszczyński", ["Bielski", "Cieszyński", "m. Jastrzębie-Zdrój", "Mikołowski", "Oświęcimski", "Bieruńsko-Lędziński", "m. Tychy", "m. Żory"] ),
                         ( "Raciborski", ["Gliwicki", "Głubczycki", "Kędzierzyńsko-Kozielski", "Rybnicki", "m. Rybnik", "Wodzisławski"] ),
                         ( "Rybnicki", ["Gliwicki", "m. Jastrzębie-Zdrój", "Mikołowski", "Raciborski", "m. Rybnik", "Wodzisławski", "m. Żory"] ),
                         ( "Tarnogórski", ["Będziński", "m. Bytom", "Gliwicki", "m. Gliwice", "Lubliniecki", "Myszkowski", "m. Piekary Śląskie", "Strzelecki", "m. Zabrze"] ),
                         ( "Wodzisławski", ["m. Jastrzębie-Zdrój", "Raciborski", "Rybnicki", "m. Rybnik"] ),
                         ( "Zawierciański", ["Będziński", "Częstochowski", "m. Dąbrowa Górnicza", "Jędrzejowski", "Miechowski", "Myszkowski", "Olkuski", "Włoszczowski"] ),
                         ( "Żywiecki", ["Bielski", "Cieszyński", "Suski", "Wadowicki"] )]},
           {"provinceName": "Świętokrzyskie",
            "counties": [( "Buski", ["Dąbrowski", "Kazimierski", "Kielecki", "Pińczowski", "Staszowski"] ),
                         ( "Jędrzejowski", ["Kielecki", "Miechowski", "Pińczowski", "Włoszczowski", "Zawierciański"] ),
                         ( "Kazimierski", ["Buski", "Dąbrowski", "Miechowski", "Pińczowski", "Proszowicki"] ),
                         ( "Kielecki", ["Buski", "Jędrzejowski", "m. Kielce", "Konecki", "Opatowski", "Ostrowiecki", "Pińczowski", "Skarżyski", "Starachowicki", "Staszowski", "Włoszczowski"] ),
                         ( "Konecki", ["Kielecki", "Opoczyński", "Przysuski", "Radomszczański", "Skarżyski", "Szydłowiecki", "Włoszczowski"] ),
                         ( "Opatowski", ["Kielecki", "Kraśnicki", "Lipski", "Opolski", "Ostrowiecki", "Sandomierski", "Staszowski"] ),
                         ( "Ostrowiecki", ["Kielecki", "Lipski", "Opatowski", "Starachowicki"] ),
                         ( "Pińczowski", ["Buski", "Jędrzejowski", "Kazimierski", "Kielecki", "Miechowski"] ),
                         ( "Sandomierski", ["Kraśnicki", "Opatowski", "Stalowowolski", "Staszowski", "Tarnobrzeski", "m. Tarnobrzeg"] ),
                         ( "Skarżyski", ["Kielecki", "Konecki", "Starachowicki", "Szydłowiecki"] ),
                         ( "Starachowicki", ["Kielecki", "Lipski", "Ostrowiecki", "Radomski", "Skarżyski", "Szydłowiecki"] ),
                         ( "Staszowski", ["Buski", "Dąbrowski", "Kielecki", "Mielecki", "Opatowski", "Sandomierski", "Tarnobrzeski"] ),
                         ( "Włoszczowski", ["Częstochowski", "Jędrzejowski", "Kielecki", "Konecki", "Radomszczański", "Zawierciański"] )]},
           {"provinceName": "Warmińsko-Mazurskie",
            "counties": [( "Bartoszycki", ["Braniewski", "Kętrzyński", "Lidzbarski", "Olsztyński"] ),
                         ( "Braniewski", ["Bartoszycki", "Elbląski", "Lidzbarski"] ),
                         ( "Działdowski", ["Brodnicki", "Iławski", "Mławski", "Nidzicki", "Nowomiejski", "Ostródzki", "Żuromiński"] ),
                         ( "Elbląski", ["Braniewski", "m. Elbląg", "Lidzbarski", "Malborski", "Nowodworski", "Ostródzki", "Sztumski"] ),
                         ( "Ełcki", ["Augustowski", "Giżycki", "Grajewski", "Olecki", "Piski", "Suwalski"] ),
                         ( "Giżycki", ["Ełcki", "Gołdapski", "Kętrzyński", "Mrągowski", "Olecki", "Piski", "Węgorzewski"] ),
                         ( "Gołdapski", ["Giżycki", "Olecki", "Suwalski", "Węgorzewski"] ),
                         ( "Iławski", ["Działdowski", "Grudziądzki", "Kwidzyński", "Nowomiejski", "Ostródzki", "Sztumski"] ),
                         ( "Kętrzyński", ["Bartoszycki", "Giżycki", "Mrągowski", "Olsztyński"] ),
                         ( "Lidzbarski", ["Bartoszycki", "Braniewski", "Elbląski", "Olsztyński", "Ostródzki"] ),
                         ( "Mrągowski", ["Giżycki", "Kętrzyński", "Olsztyński", "Piski", "Szczycieński"] ),
                         ( "Nidzicki", ["Działdowski", "Mławski", "Olsztyński", "Ostródzki", "Przasnyski", "Szczycieński"] ),
                         ( "Nowomiejski", ["Brodnicki", "Działdowski", "Grudziądzki", "Iławski"] ),
                         ( "Olecki", ["Ełcki", "Giżycki", "Gołdapski", "Suwalski"] ),
                         ( "Olsztyński", ["Bartoszycki", "Kętrzyński", "Lidzbarski", "Mrągowski", "Nidzicki", "m. Olsztyn", "Ostródzki", "Szczycieński"] ),
                         ( "Ostródzki", ["Działdowski", "Elbląski", "Iławski", "Lidzbarski", "Nidzicki", "Olsztyński", "Sztumski"] ),
                         ( "Piski", ["Ełcki", "Giżycki", "Grajewski", "Kolneński", "Mrągowski", "Ostrołęcki", "Szczycieński"] ),
                         ( "Szczycieński", ["Mrągowski", "Nidzicki", "Olsztyński", "Ostrołęcki", "Piski", "Przasnyski"] ),
                         ( "Węgorzewski", ["Giżycki", "Gołdapski", "Kętrzyński"] )]},
           {"provinceName": "Wielkopolskie",
            "counties": [( "Chodzieski", ["Czarnkowsko-Trzcianecki", "Obornicki", "Pilski", "Wągrowiecki"] ),
                         ( "Czarnkowsko-Trzcianecki", ["Chodzieski", "Międzychodzki", "Obornicki", "Pilski", "Strzelecko-Drezdenecki", "Szamotulski", "Wałecki"] ),
                         ( "Gnieźnieński", ["Mogileński", "Poznański", "Słupecki", "Wągrowiecki", "Wrzesiński", "Żniński"] ),
                         ( "Gostyński", ["Jarociński", "Kościański", "Krotoszyński", "Leszczyński", "Rawicki", "Śremski"] ),
                         ( "Grodziski", ["Kościański", "Nowotomyski", "Poznański", "Wolsztyński"] ),
                         ( "Jarociński", ["Gostyński", "Krotoszyński", "Pleszewski", "Śremski", "Średzki", "Wrzesiński"] ),
                         ( "Kaliski", ["m. Kalisz", "Koniński", "Ostrowski", "Ostrzeszowski", "Pleszewski", "Sieradzki", "Turecki"] ),
                         ( "Kępiński", ["Kluczborski", "Namysłowski", "Oleśnicki", "Ostrzeszowski", "Wieruszowski"] ),
                         ( "Kolski", ["Koniński", "Kutnowski", "Łęczycki", "Poddębicki", "Turecki", "Włocławski"] ),
                         ( "Koniński", ["Kaliski", "Kolski", "m. Konin", "Mogileński", "Pleszewski", "Radziejowski", "Słupecki", "Turecki"] ),
                         ( "Kościański", ["Gostyński", "Grodziski", "Leszczyński", "Poznański", "Śremski", "Wolsztyński"] ),
                         ( "Krotoszyński", ["Gostyński", "Jarociński", "Milicki", "Ostrowski", "Pleszewski", "Rawicki"] ),
                         ( "Leszczyński", ["Gostyński", "Górowski", "Kościański", "m. Leszno", "Rawicki", "Wolsztyński", "Wschowski"] ),
                         ( "Międzychodzki", ["Czarnkowsko-Trzcianecki", "Międzyrzecki", "Nowotomyski", "Strzelecko-Drezdenecki", "Szamotulski"] ),
                         ( "Nowotomyski", ["Grodziski", "Międzychodzki", "Międzyrzecki", "Poznański", "Szamotulski", "Świebodziński", "Wolsztyński", "Zielonogórski"] ),
                         ( "Obornicki", ["Chodzieski", "Czarnkowsko-Trzcianecki", "Poznański", "Szamotulski", "Wągrowiecki"] ),
                         ( "Ostrowski", ["m. Kalisz", "Kaliski", "Krotoszyński", "Milicki", "Oleśnicki", "Ostrzeszowski", "Pleszewski"] ),
                         ( "Ostrzeszowski", ["Kaliski", "Kępiński", "Oleśnicki", "Ostrowski", "Sieradzki", "Wieruszowski"] ),
                         ( "Pilski", ["Chodzieski", "Czarnkowsko-Trzcianecki", "Nakielski", "Sępoleński", "Wałecki", "Wągrowiecki", "Złotowski"] ),
                         ( "Pleszewski", ["Jarociński", "m. Kalisz", "Kaliski", "Koniński", "Krotoszyński", "Ostrowski", "Słupecki", "Wrzesiński"] ),
                         ( "Poznański", ["Gnieźnieński", "Grodziski", "Kościański", "Nowotomyski", "Obornicki", "m. Poznań", "Szamotulski", "Śremski", "Średzki", "Wągrowiecki", "Wrzesiński"] ),
                         ( "Rawicki", ["Gostyński", "Górowski", "Krotoszyński", "Leszczyński", "Milicki", "Trzebnicki"] ),
                         ( "Słupecki", ["Gnieźnieński", "Koniński", "Mogileński", "Pleszewski", "Wrzesiński"] ),
                         ( "Szamotulski", ["Czarnkowsko-Trzcianecki", "Międzychodzki", "Nowotomyski", "Obornicki", "Poznański"] ),
                         ( "Średzki", ["Jarociński", "Poznański", "Śremski", "Wrzesiński"] ),
                         ( "Śremski", ["Gostyński", "Jarociński", "Kościański", "Poznański", "Średzki"] ),
                         ( "Turecki", ["Kaliski", "Kolski", "Koniński", "Poddębicki", "Sieradzki"] ),
                         ( "Wągrowiecki", ["Chodzieski", "Gnieźnieński", "Nakielski", "Obornicki", "Pilski", "Poznański", "Żniński"] ),
                         ( "Wolsztyński", ["Grodziski", "Kościański", "Leszczyński", "Nowosolski", "Nowotomyski", "Wschowski", "Zielonogórski"] ),
                         ( "Wrzesiński", ["Gnieźnieński", "Jarociński", "Pleszewski", "Poznański", "Słupecki", "Średzki"] ),
                         ( "Złotowski", ["Człuchowski", "Drawski", "Pilski", "Sępoleński", "Szczecinecki", "Wałecki"] )]},
           {"provinceName": "Zachodniopomorskie",
            "counties": [( "Białogardzki", ["Kołobrzeski", "Koszaliński", "Szczecinecki", "Świdwiński"] ),
                         ( "Choszczeński", ["Drawski", "Myśliborski", "Stargardzki", "Strzelecko-Drezdenecki", "Wałecki"] ),
                         ( "Drawski", ["Choszczeński", "Łobeski", "Stargardzki", "Szczecinecki", "Świdwiński", "Wałecki"] ),
                         ( "Goleniowski", ["Gryficki", "Kamieński", "Łobeski", "Policki", "Stargardzki", "m. Szczecin", "m. Świnoujście"] ),
                         ( "Gryficki", ["Goleniowski", "Kamieński", "Kołobrzeski", "Łobeski"] ),
                         ( "Gryfiński", ["Myśliborski", "Policki", "Pyrzycki", "Stargardzki", "m. Szczecin"] ),
                         ( "Kamieński", ["Goleniowski", "Gryficki", "m. Świnoujście"] ),
                         ( "Kołobrzeski", ["Białogardzki", "Gryficki", "Koszaliński", "Łobeski", "Świdwiński"] ),
                         ( "Koszaliński", ["Białogardzki", "Bytowski", "Kołobrzeski", "m. Koszalin", "Sławieński", "Słupski", "Szczecinecki"] ),
                         ( "Łobeski", ["Drawski", "Goleniowski", "Gryficki", "Kołobrzeski", "Stargardzki", "Świdwiński"] ),
                         ( "Myśliborski", ["Choszczeński", "Gorzowski", "Gryfiński", "Pyrzycki", "Strzelecko-Drezdenecki"] ),
                         ( "Policki", ["Goleniowski", "Gryfiński", "m. Szczecin", "m. Świnoujście"] ),
                         ( "Pyrzycki", ["Gryfiński", "Myśliborski", "Stargardzki"] ),
                         ( "Sławieński", ["Koszaliński", "Słupski"] ),
                         ( "Stargardzki", ["Choszczeński", "Drawski", "Goleniowski", "Gryfiński", "Łobeski", "Pyrzycki", "m. Szczecin"] ),
                         ( "Szczecinecki", ["Białogardzki", "Bytowski", "Człuchowski", "Drawski", "Koszaliński", "Świdwiński", "Złotowski"] ),
                         ( "Świdwiński", ["Białogardzki", "Drawski", "Kołobrzeski", "Łobeski", "Szczecinecki"] ),
                         ( "Wałecki", ["Choszczeński", "Czarnkowsko-Trzcianecki", "Drawski", "Pilski", "Strzelecko-Drezdenecki", "Złotowski"] )]}]

